
def add_calc_parser_common(subparser):

    subparser.add_argument("-d", "--directory", type=str, default="atomsciflow-calc-running-dir",
        help="The working directory where calculation is happening")

    subparser.add_argument("--runopt", type=str, default="gen",
        choices=["gen", "run", "genrun"],
        help="The running option. gen -> only generate the files; run -> run the calculation generated by previous gen; genrun -> generation and run the calculation")

    subparser.add_argument("-a", "--auto-level", type=int, default=0,
        choices=[0, 1, 2, 3],
        help="The automation level of the task")

    subparser.add_argument("--server", type=str, default="pbs",
        choices=["pbs", "llhpc", "yhbatch", "lsf_sz", "lsf_sustc", "cdcloud"])

def set_calc_processor_common(calc, args):
    calc.job.set_run("runopt", args.runopt)
    calc.job.set_run("server", args.server)    
